[programs.devnet]
myepicproject = "DWJoeHYV3uGGmWbEBmgzmiZbBrjbVNPBcMBYprehjyWo"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/eduardomp/.config/solana/devnet-01.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
